export enum ACCOUNT_TYPE {
    ADMIN = 'ADMIN',
    MANAHGER = 'MANAHGER',
    TELLER = 'TELLER',
    CUSTOMER = 'CUSTOMER',
}


export enum BANK_ACC_TYPE {
    SAVINGS = 'SAVINGS',
    CHECKING = 'CHECKING'
}